const profiles = [
  {
    title: "Happy House! ",
    name: "Nuttawut",
    eid: "1",
    picture: "https://zljerlfbpexcqsayzrqs.supabase.co/storage/v1/object/sign/img/images.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJpbWcvaW1hZ2VzLmpwZyIsImlhdCI6MTcyMDQyNDc4NiwiZXhwIjoxNzUxOTYwNzg2fQ.PLuGd4c78m0cW7LEvKPE9t7gSCKyUPBXE84U62ROs8U&t=2024-07-08T07%3A46%3A25.556Z",
    url: "https://www.wongnai.com/trips/travel-koh-chang",
    description: "lorm",
    addess: "Senanikrom, Korat",
    type: ["Dog", "Cat"],
    rating: 5,
    year:"0-2 year",
  },{
    title: "Majin House ",
    name: "Jame Masion",
    eid: "2",
    picture: "https://zljerlfbpexcqsayzrqs.supabase.co/storage/v1/object/sign/img/images.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJpbWcvaW1hZ2VzLmpwZyIsImlhdCI6MTcyMDQyNDc4NiwiZXhwIjoxNzUxOTYwNzg2fQ.PLuGd4c78m0cW7LEvKPE9t7gSCKyUPBXE84U62ROs8U&t=2024-07-08T07%3A46%3A25.556Z",

    url: "https://www.wongnai.com/trips/travel-koh-chang",
    description: "lorm",
    addess: "Senanikrom, Nan",
    type: ["Dog", "Cat", "Bird", "Rabbit"],
    rating: 2,
    year: "3-5 year",
  },{
    title: "Cat OnlyOne ",
    name: "Jame Masion",
    eid: "3",
    picture: "https://zljerlfbpexcqsayzrqs.supabase.co/storage/v1/object/sign/img/images.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJpbWcvaW1hZ2VzLmpwZyIsImlhdCI6MTcyMDQyNDc4NiwiZXhwIjoxNzUxOTYwNzg2fQ.PLuGd4c78m0cW7LEvKPE9t7gSCKyUPBXE84U62ROs8U&t=2024-07-08T07%3A46%3A25.556Z",
    url: "https://www.wongnai.com/trips/travel-koh-chang",
    description: "lorm",
    addess: "Senanikrom, Ubon",
    type: ["Dog", "Cat", "Rabbit"],
    rating:  3,
    year:  "5+ year",
  },{
    title: "Happy House! ",
    name: "Jame Masion",
    eid: "4",
    picture: "https://zljerlfbpexcqsayzrqs.supabase.co/storage/v1/object/sign/img/images.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJpbWcvaW1hZ2VzLmpwZyIsImlhdCI6MTcyMDQyNDc4NiwiZXhwIjoxNzUxOTYwNzg2fQ.PLuGd4c78m0cW7LEvKPE9t7gSCKyUPBXE84U62ROs8U&t=2024-07-08T07%3A46%3A25.556Z",
    url: "https://www.wongnai.com/trips/travel-koh-chang",
    description: "lorm",
    addess: "Senanikrom, Khonkeng",
    type: [ "Bird", "Rabbit"],
    rating: 5,
    year: "0-2 year",
  },{
    title: "Happy House! ",
    name: "Jame Masion",
    eid: "5",
    picture: "https://zljerlfbpexcqsayzrqs.supabase.co/storage/v1/object/sign/img/images.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJpbWcvaW1hZ2VzLmpwZyIsImlhdCI6MTcyMDQyNDc4NiwiZXhwIjoxNzUxOTYwNzg2fQ.PLuGd4c78m0cW7LEvKPE9t7gSCKyUPBXE84U62ROs8U&t=2024-07-08T07%3A46%3A25.556Z",
    url: "https://www.wongnai.com/trips/travel-koh-chang",
    description: "lorm",
    addess: "Senanikrom, Chengmai",
    type: [ "Cat", "Rabbit"],
    rating:  3 ,
    year:  "3-5 year",
  },{
    title: "Happy House! ",
    name: "Jame Masion",
    eid: "6",
    picture: "https://zljerlfbpexcqsayzrqs.supabase.co/storage/v1/object/sign/img/images.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJpbWcvaW1hZ2VzLmpwZyIsImlhdCI6MTcyMDQyNDc4NiwiZXhwIjoxNzUxOTYwNzg2fQ.PLuGd4c78m0cW7LEvKPE9t7gSCKyUPBXE84U62ROs8U&t=2024-07-08T07%3A46%3A25.556Z",
    url: "https://www.wongnai.com/trips/travel-koh-chang",
    description: "lorm",
    addess: "Senanikrom, Bangkok",
    type: ["Dog", "Cat", "Bird"],
    rating: 4,
    year: "0-2 year",
  },{
    title: "Happy House! ",
    name: "Jame Masion",
    eid: "7",
    picture: "https://zljerlfbpexcqsayzrqs.supabase.co/storage/v1/object/sign/img/images.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJpbWcvaW1hZ2VzLmpwZyIsImlhdCI6MTcyMDQyNDc4NiwiZXhwIjoxNzUxOTYwNzg2fQ.PLuGd4c78m0cW7LEvKPE9t7gSCKyUPBXE84U62ROs8U&t=2024-07-08T07%3A46%3A25.556Z",
    url: "https://www.wongnai.com/trips/travel-koh-chang",
    description: "lorm",
    addess: "Senanikrom, Bangkok",
    type: ["Dog", "Cat", "Bird", "Rabbit"],
    rating: 1,
    year:  "5+ year",
  }
];

export default profiles
